/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapaint;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javafx.scene.input.MouseDragEvent;
import javax.swing.JColorChooser;
import javax.swing.JPanel;

/**
 *
 * @author pedrecal
 */
public class GUI extends javax.swing.JFrame {

    int mouseX, mouseY;
    int mouseX_released, mouseY_released;
    int mouseX_dragged, mouseY_dragged;
    int firstX, firstY;
    boolean mouseDragged;
    boolean firstClick;
    JPanel panel;
    Graphics g;
    Color c;
    String tipo;
    ArrayList<Desenho> desenhus = new ArrayList();
    
    public GUI() {
        initComponents();
        
        tipo = null;
        firstClick = false;
        
        addMouseListener(myMouseAdapter);
        addMouseMotionListener(myMouseAdapter);
        
        panel = new JPanel();
        panel.setSize(600, 600);
        this.add(panel);
        panel.setVisible(true);
        panel.setBackground(Color.WHITE);
        
        g = panel.getGraphics();
    }
    
    MouseAdapter myMouseAdapter = new MouseAdapter() 
    {
            public void mousePressed(MouseEvent e)
            {
                mouseX = e.getX();
                mouseY = e.getY();
                mouseDragged = false;
                if (tipo == "free hand")
                    new FreeHand(mouseX, mouseY, g, c);                
                
            }
            
            public void mouseDragged(MouseEvent e)
            {
                mouseX_dragged = e.getX();
                mouseY_dragged = e.getY();
                mouseDragged = true;
                
                if (tipo == "Linha Livre")
                {
                    Desenho livre = new FreeHand(mouseX_dragged, mouseY_dragged, g, c);
                    livre.Desenha();
                    desenhus.add(livre);
                }
                else if(tipo == "Borracha")
                {
                    Desenho borracha = new Ereaser(mouseX_dragged, mouseY_dragged, panel);
                    borracha.Desenha();
                    desenhus.add(borracha);
                }
            }
            
            public void mouseReleased(MouseEvent e)
            {
                mouseX_released = e.getX();
                mouseY_released = e.getY();
                if(mouseDragged)
                {
                    if(tipo == "Linha Reta")
                    {
                        Desenho linha = new Line(mouseX, mouseY, mouseX_released, mouseY_released, g, c);
                        linha.Desenha();
                        desenhus.add(linha);
                    }
                    else if(tipo == "Retangulo")
                    {
                       Desenho retangulo = new Rectangle(mouseX, mouseY, mouseX_released, mouseY_released, g, c);
                       retangulo.Desenha();
                       desenhus.add(retangulo);
                    }
                    else if(tipo == "Circulo")
                    {
                        Desenho circulo = new Elipse(mouseX, mouseY, mouseX_dragged, mouseY_dragged, g, c);
                        circulo.Desenha();
                        desenhus.add(circulo);
                    }
                    else
                        System.out.println("Nenhuma opção selecionada");
                    mouseDragged = false;
                }
            }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ferramentas", "Linha Reta", "Linha Livre", "Retangulo", "Circulo", "Borracha" }));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Editar", "Cor", "Limpar Tela" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        if ("Cor".equals((String) jComboBox1.getSelectedItem()))
        {
            c = JColorChooser.showDialog(rootPane, null, Color.BLACK);
        }
        else if("Limpar Tela".equals((String) jComboBox1.getSelectedItem()))
        {
            repaint();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        tipo = (String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        repaint();
        for(int i = 0; i < desenhus.size(); i++)
            desenhus.get(i).Desenha();
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    // End of variables declaration//GEN-END:variables
}
